language: node_js

node_js:
  - node

env:
  - NODE_ENV=test

before_install:
  - npm install -g codecov

script:
  - npm run travis-test
  - codecov

after_success: bash <(curl -s https://codecov.io/bash)
